language: ruby
cache: bundler
bundler_args: --without optional

jdk:
  - oraclejdk7

services:
  - mongodb

rvm:
  - 1.9.3
  - 2.1.6
  - 2.2.2
  - jruby-19mode
  - rbx-19mode
  - rbx-2.5.3

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: rbx-2.5.3
